# Pertemuan 11
## Sustainable Logistics

### Kasus

Distribusi beras dari Lampung ke Jakarta menggunakan tiga moda:
- Truk diesel
- Kereta api
- Kapal laut

---
## 1. Dataset Moda Transportasi

In [1]:
import pandas as pd

moda = pd.DataFrame({
    'moda':          ['Truk Diesel', 'Kereta Api', 'Kapal Laut'],
    'emisi_co2_kg':  [850,           210,          320],    # kg CO2 per ton muatan
    'biaya_rp':      [4500000,       2800000,      1900000], # Rp per ton
    'lead_time_jam': [12,            18,            48],     # jam
    'kapasitas_ton': [10,            500,           5000],
})

moda

          moda  emisi_co2_kg  biaya_rp  lead_time_jam  kapasitas_ton
0  Truk Diesel           850   4500000             12             10
1   Kereta Api           210   2800000             18            500
2   Kapal Laut           320   1900000             48           5000

---
## 2. Sustainability Score

In [2]:
# Normalisasi: skor lebih rendah = lebih berkelanjutan
df = moda.copy()
df['emisi_norm']  = df['emisi_co2_kg'] / df['emisi_co2_kg'].max()
df['biaya_norm']  = df['biaya_rp']     / df['biaya_rp'].max()
df['waktu_norm']  = df['lead_time_jam']/ df['lead_time_jam'].max()

# Bobot: emisi 50%, biaya 30%, waktu 20%
df['sustainability_score'] = (
    df['emisi_norm'] * 0.5 +
    df['biaya_norm'] * 0.3 +
    df['waktu_norm'] * 0.2
).round(3)

df[['moda', 'emisi_co2_kg', 'biaya_rp', 'lead_time_jam', 'sustainability_score']].sort_values('sustainability_score')

          moda  emisi_co2_kg  biaya_rp  lead_time_jam  sustainability_score
1   Kereta Api           210   2800000             18                 0.385
2   Kapal Laut           320   1900000             48                 0.515
0  Truk Diesel           850   4500000             12                 0.850

---
## 3. AI Sustainability Advisor (Groq)

In [3]:
import os
from dotenv import load_dotenv
from groq import Groq

load_dotenv()
client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

data_str = moda.to_string(index=False)

prompt = f"""
Berikut data moda transportasi distribusi beras dari Lampung ke Jakarta:

{data_str}

Moda mana yang paling berkelanjutan untuk distribusi beras dari Lampung ke Jakarta?
Pertimbangkan emisi karbon, biaya, dan lead time.
Berikan rekomendasi dan alasannya.
"""

response = client.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[{"role": "user", "content": prompt}]
)

print(response.choices[0].message.content)

Berdasarkan data yang diberikan, moda transportasi yang paling berkelanjutan untuk distribusi beras dari Lampung ke Jakarta dapat dianalisis dengan mempertimbangkan emisi karbon, biaya, dan lead time.

1. **Emisi Karbon (CO2)**: Kereta Api memiliki emisi karbon yang paling rendah, yaitu 210 kg.
2. **Biaya**: Kapal Laut memiliki biaya yang paling rendah, yaitu Rp 1.900.000.
3. **Lead Time**: Truk Diesel memiliki lead time yang paling singkat, yaitu 12 jam.

Namun, jika kita mempertimbangkan ketiga faktor tersebut secara keseluruhan, maka Kereta Api dapat menjadi pilihan yang paling berkelanjutan. Berikut alasannya:

- **Emisi Karbon**: Kereta Api memiliki emisi karbon yang paling rendah, yaitu 210 kg, yang berarti lebih ramah lingkungan dibandingkan dengan Truk Diesel (850 kg) dan Kapal Laut (320 kg).
- **Biaya**: Meskipun biaya Kereta Api (Rp 2.800.000) lebih tinggi daripada Kapal Laut (Rp 1.900.000), namun biaya tersebut masih relatif kompetitif jika dibandingkan dengan Truk Diesel (Rp 4.500.000).
- **Lead Time**: Lead time Kereta Api (18 jam) lebih lama daripada Truk Diesel (12 jam), namun relatif lebih singkat daripada Kapal Laut (48 jam).

Dengan demikian, rekomendasi moda transportasi yang paling berkelanjutan untuk distribusi beras dari Lampung ke Jakarta adalah Kereta Api, karena memiliki emisi karbon yang paling rendah, biaya yang relatif kompetitif, dan lead time yang masih dapat diterima.

---
## 4. Nilai SI: Chatbot Keberlanjutan

Bangun chatbot interaktif yang menjawab pertanyaan seputar keberlanjutan logistik.

In [4]:
history = []

def chat_sustainability(pertanyaan: str) -> str:
    history.append({"role": "user", "content": pertanyaan})
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": "Kamu adalah ahli logistik berkelanjutan. Jawab dalam Bahasa Indonesia."},
            *history
        ]
    )
    reply = response.choices[0].message.content
    history.append({"role": "assistant", "content": reply})
    return reply

# Contoh penggunaan
print(chat_sustainability("Bagaimana cara mengurangi emisi karbon dalam distribusi beras?"))

Sebagai ahli logistik berkelanjutan, saya memiliki beberapa saran untuk mengurangi emisi karbon dalam distribusi beras:

1. **Optimalkan Rute Pengiriman**: Menggunakan sistem navigasi dan perangkat lunak untuk mengoptimalkan rute pengiriman dapat mengurangi jarak tempuh dan waktu pengiriman, sehingga mengurangi emisi karbon.
2. **Gunakan Kendaraan yang Efisien**: Menggunakan kendaraan yang lebih efisien dan ramah lingkungan, seperti kendaraan listrik atau hibrida, dapat mengurangi emisi karbon.
3. **Konsolidasi Pengiriman**: Menggabungkan beberapa pengiriman dalam satu kendaraan dapat mengurangi jumlah kendaraan yang digunakan dan mengurangi emisi karbon.
4. **Gunakan Transportasi Multimoda**: Menggunakan kombinasi transportasi darat, laut, dan udara dapat mengurangi emisi karbon dan meningkatkan efisiensi pengiriman.
5. **Implementasi Sistem Manajemen Logistik**: Menggunakan sistem manajemen logistik yang canggih dapat membantu mengoptimalkan proses pengiriman, mengurangi waktu tunggu, dan mengurangi emisi karbon.
6. **Gunakan Bahan Kemasan yang Ramah Lingkungan**: Menggunakan bahan kemasan yang ramah lingkungan, seperti kertas atau karton, dapat mengurangi jumlah sampah dan emisi karbon.
7. **Mengurangi Penggunaan Kemasan**: Mengurangi penggunaan kemasan secara keseluruhan dapat mengurangi jumlah sampah dan emisi karbon.
8. **Gunakan Energi Terbarukan**: Menggunakan energi terbarukan, seperti energi surya atau angin, dapat mengurangi emisi karbon dalam proses pengiriman.
9. **Mengembangkan Sistem Pengiriman yang Berkelanjutan**: Mengembangkan sistem pengiriman yang berkelanjutan, seperti pengiriman pada malam hari atau menggunakan kendaraan yang lebih kecil, dapat mengurangi emisi karbon.
10. **Mengukur dan Mengurangi Emisi Karbon**: Mengukur emisi karbon dan mengembangkan strategi untuk menguranginya dapat membantu mengurangi dampak lingkungan dari distribusi beras.

Dengan menerapkan strategi-strategi di atas, kita dapat mengurangi emisi karbon dalam distribusi beras dan membuat industri beras lebih berkelanjutan.

In [5]:
print(chat_sustainability("halo"))

Halo! Selamat datang! Apakah ada yang bisa saya bantu?